#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

##### Copy files ################################
cd constant
cp -rf polyMesh.orig polyMesh
cd ..
cp -rf 0.orig 0

###### Run solver and restore results ###########
runApplication $(getApplication)


#runApplication decomposePar
#runParallel $(getApplication)
#runApplication reconstructPar
